openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: A sample API for testing CurlMan
servers:
  - url: https://jsonplaceholder.typicode.com
    description: JSONPlaceholder API
paths:
  /posts:
    get:
      summary: Get all posts
      operationId: getPosts
      parameters:
        - name: userId
          in: query
          schema:
            type: integer
          description: Filter by user ID
      responses:
        '200':
          description: Successful response
    post:
      summary: Create a new post
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                userId:
                  type: integer
      responses:
        '201':
          description: Created
  /posts/{id}:
    get:
      summary: Get a post by ID
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    put:
      summary: Update a post
      operationId: updatePost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                userId:
                  type: integer
      responses:
        '200':
          description: Successful response
    delete:
      summary: Delete a post
      operationId: deletePost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: Successful response
  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
